### ISSUE TITLE
Color is mispelled

### ISSUE THREAD

**Issue by soulshake** [mux23/drewskel#1]
_Color_ is incorrectly spelled as _colour_ multiple times, e.g. https://github.com/mux23/drewskel/blob/master/.bash_profile#L31

Please advise ASAP

**Comment by mux23** [comment]
problem has been identified as the failing of the public education system in the colonies. marking 'works for me' and closing this ticket.

**Comment by soulshake** [comment]
Wow they let just about anybody use a computer these days, don't they? UGHHH
